### ISSUE TITLE
Can't get the author link to work

### ISSUE THREAD

**Issue by ellenmonster** [epid8060fall2019/EllenCheng-dataanalysis#1]
When I copy-paste the author link that I have in my author.Rmd file, I get to the correct author website. But when I go to the project website itself and try the Author menu pull-down, it says it's missing an index file and it doesn't show my author website. I thought I didn't 'knit' the author.Rmd before pushing to Github so I tried that and just pushed the new author.html to the class Github, but it's still not working

**Comment by andreashandel** [comment]
see if the reply I gave to Megan on eLC might fix yours too. Looks like the same issue.

**Comment by ellenmonster** [comment]
Fixed, thank you! I also posted a reply to Megan's question--I combined your suggestion with also changing all the 'author' references back to capital instead of lowercase
